import Head from 'next/head';
import Link from 'next/link';

import styles from '@/styles/Home.module.css';

export default function Home() {
  return (
    <>
      <Head>
        <title>Next.js 13 POC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>테스트 페이지들</h1>
        <div>
          <ul>
            <li>
              <Link href="/poc/profile-sign-up">ProfileSignUp</Link>
            </li>
          </ul>
        </div>
      </main>
    </>
  )
}
